var municipiosPorEstado = {
  "Aguascalientes": ["Aguascalientes", "Asientos", "Calvillo", "Cosío", "El Llano", "Jesús María", "Pabellón", "Rincón de Romos", "San Francisco de los Romo", "San José de Gracia", "Tepezalá"],
  "Baja California": ["Ensenada", "Mexicali", "Tecate", "Tijuana", "Playas de Rosarito"],
  "Baja California Sur": ["Comondú", "La Paz", "Loreto", "Los Cabos", "Mulegé"],
  "Campeche": ["Calakmul", "Calkiní", "Campeche", "Candelaria", "Champotón", "Hecelchakán", "Hopelchén", "Palizada", "Tenabo", "Escárcega"],
  "Coahuila": ["Acuña", "Allende", "Arteaga", "Candela", "Castaños", "Cuatro Ciénegas", "Escobedo", "Francisco I. Madero", "Frontera", "General Cepeda", "Guerrero", "Hidalgo", "Jiménez", "Juárez", "Lamadrid", "Matamoros", "Monclova", "Morelos", "Múzquiz", "Nadadores", "Nava", "Ocampo", "Parras", "Piedras Negras", "Progreso", "Ramos Arizpe", "Sabinas", "Sacramento", "Saltillo", "San Buenaventura", "San Juan de Sabinas", "San Pedro", "Sierra Mojada", "Torreón", "Viesca", "Villa Unión", "Zaragoza"],
  "Colima": ["Armería", "Colima", "Comala", "Coquimatlán", "Cuauhtémoc", "Ixtlahuacán", "Manzanillo", "Minatitlán", "Tecomán", "Villa de Álvarez"],
  "Chiapas": ["Acacoyagua", "Acala", "Acapetahua", "Altamirano", "Amatán", "Amatenango de la Frontera", "Amatenango del Valle", "Angel Albino Corzo", "Arriaga", "Bejucal de Ocampo", "Bella Vista", "Benemérito de las Américas", "Berriozábal", "Bochil", "El Bosque", "Cacahoatán", "Catazajá", "Cintalapa", "Coapilla", "Comitán de Domínguez", "La Concordia", "Copainalá", "Chalchihuitán", "Chamula", "Chanal", "Chapultenango", "Chenalhó", "Chiapa de Corzo", "Chiapilla", "Chicoasén", "Chicomuselo", "Chilón", "Escuintla", "Francisco León", "Frontera Comalapa", "Frontera Hidalgo", "La Grandeza", "Huehuetán", "Huixtán", "Huitiupán", "Huixtla", "La Independencia", "Ixhuatán", "Ixtacomitán", "Ixtapa", "Ixtapangajoya", "Jiquipilas", "Jitotol", "Juárez", "Larráinzar", "La Libertad", "Mapastepec", "Las Margaritas", "Mazatán", "Motozintla", "Nicolás Ruíz", "Ocosingo", "Ocotepec", "Ocozocoautla de Espinosa", "Ostuacán", "Osumacinta", "Oxchuc", "Palenque", "Pantelhó", "Pantepec", "Pichucalco", "Pijijiapan", "El Porvenir", "Villa Corzo", "Pueblo Nuevo Solistahuacán", "Rayón", "Reforma", "Las Rosas", "Sabanilla", "Salto de Agua", "San Cristóbal de las Casas", "San Fernando", "Siltepec", "Simojovel", "Sitalá", "Socoltenango", "Solosuchiapa", "Soyaló", "Suchiapa", "Suchiate", "Sunuapa", "Tapachula", "Tapalapa", "Tapilula", "Tecpatán", "Tenejapa", "Teopisca", "Tila", "Tonalá", "Totolapa", "La Trinitaria", "Tumbalá", "Tuxtla Chico", "Tuxtla Gutiérrez", "Tuzantán", "Tzimol", "Unión Juárez", "Venustiano Carranza", "Villa Comaltitlán", "Villa Corzo", "Villaflores", "Yajalón", "San Lucas", "Zinacantán"],
  "Chihuahua": ["Ahumada", "Aldama", "Allende", "Aquiles Serdán", "Ascensión", "Bachíniva", "Balleza", "Batopilas", "Bocoyna", "Buenaventura", "Camargo", "Carichí", "Casas Grandes", "Coronado", "Coyame del Sotol", "La Cruz", "Cuauhtémoc", "Cusihuiriachi", "Chihuahua", "Chínipas", "Delicias", "Dr. Belisario Domínguez", "Galeana", "Santa Isabel", "Gómez Farías", "Gran Morelos", "Guachochi", "Guadalupe", "Guadalupe y Calvo", "Guazapares", "Guerrero", "Hidalgo del Parral", "Huejotitán", "Ignacio Zaragoza", "Janos", "Jiménez", "Juárez", "Julimes", "López", "Madera", "Maguarichi", "Manuel Benavides", "Matachí", "Matamoros", "Meoqui", "Morelos", "Moris", "Namiquipa", "Nonoava", "Nuevo Casas Grandes", "Ocampo", "Ojinaga", "Praxedis G. Guerrero", "Riva Palacio", "Rosales", "Rosario", "San Francisco de Borja", "San Francisco de Conchos", "San Francisco del Oro", "Santa Bárbara", "Satevó", "Saucillo", "Temósachi", "El Tule", "Urique", "Uruachi", "Valle de Zaragoza"],
  "Ciudad de México": ["Azcapotzalco", "Coyoacán", "Cuajimalpa de Morelos", "Gustavo A. Madero","Iztacalco", "Iztapalapa", "La Magdalena Contreras", "Milpa Alta", "Álvaro Obregón", "Tláhuac", "Tlalpan", "Xochimilco", "Benito Juárez", "Cuauhtémoc", "Miguel Hidalgo", "Venustiano Carranza"],
  "Coahuila": ["Abasolo", "Acuña", "Allende", "Arteaga", "Candela", "Castaños", "Cuatro Ciénegas", "Escobedo", "Francisco I. Madero", "Frontera", "General Cepeda", "Guerrero", "Hidalgo", "Jiménez", "Juárez", "Lamadrid", "Matamoros", "Monclova", "Morelos", "Múzquiz", "Nadadores", "Nava", "Ocampo", "Parras", "Piedras Negras", "Progreso", "Ramos Arizpe", "Sabinas", "Sacramento", "Saltillo", "San Buenaventura", "San Juan de Sabinas", "San Pedro", "Sierra Mojada", "Torreón", "Viesca", "Villa Unión", "Zaragoza"],
  "Colima": ["Armería", "Colima", "Comala", "Coquimatlán", "Cuauhtémoc", "Ixtlahuacán", "Manzanillo", "Minatitlán", "Tecomán", "Villa de Álvarez"],
  "Durango": ["Canatlán", "Canelas", "Coneto de Comonfort", "Cuencamé", "Durango", "General Simón Bolívar", "Gómez Palacio", "Guadalupe Victoria", "Guanaceví", "Hidalgo", "Indé", "Lerdo", "Mapimí", "Mezquital", "Nazas", "Nombre de Dios", "Nuevo Ideal", "Ocampo", "El Oro", "Otáez", "Pánuco de Coronado", "Peñón Blanco", "Poanas", "Pueblo Nuevo", "Rodeo", "San Bernardo", "San Dimas", "San Juan de Guadalupe", "San Juan del Río", "San Luis del Cordero", "San Pedro del Gallo", "Santa Clara", "Santiago Papasquiaro", "Súchil", "Tamazula", "Tepehuanes", "Tlahualilo", "Topia", "Vicente Guerrero"],
  "Guanajuato": ["Abasolo", "Acámbaro", "San Miguel de Allende", "Apaseo el Alto", "Apaseo el Grande", "Atarjea", "Celaya", "Manuel Doblado", "Comonfort", "Coroneo", "Cortazar", "Cuerámaro", "Doctor Mora", "Dolores Hidalgo Cuna de la Independencia Nacional", "Guanajuato", "Huanímaro", "Irapuato", "Jaral del Progreso", "Jerécuaro", "León", "Moroleón", "Ocampo", "Pénjamo", "Pueblo Nuevo", "Purísima del Rincón", "Romita", "Salamanca", "Salvatierra", "San Diegode la Unión", "San Felipe", "San Francisco del Rincón", "San José Iturbide", "San Luis de la Paz", "Santa Catarina", "Santa Cruz de Juventino Rosas", "Santiago Maravatío", "Silao", "Tarandacuao", "Tarimoro", "Tierra Blanca", "Uriangato", "Valle de Santiago", "Victoria", "Villagrán", "Xichú", "Yuriria"],
  "Guerrero": ["Acapulco de Juárez", "Ahuacuotzingo", "Ajuchitlán del Progreso", "Alcozauca de Guerrero", "Alpoyeca", "Apaxtla", "Arcelia", "Atenango del Río", "Atlamajalcingo del Monte", "Atlixtac", "Atoyac de Álvarez", "Ayutla de los Libres", "Azoyú", "Benito Juárez", "Buenavista de Cuéllar", "Coahuayutla de José María Izazaga", "Cocula", "Copala", "Copalillo", "Copanatoyac", "Coyuca de Benítez", "Coyuca de Catalán", "Cuajinicuilapa", "Cualác", "Cuautepec", "Cuetzala del Progreso", "Cutzamala de Pinzón", "Chilapa de Álvarez", "Chilpancingo de los Bravo", "Florencio Villarreal", "General Canuto A. Neri", "General Heliodoro Castillo", "Huamuxtitlán", "Huitzuco de los Figueroa", "Iguala de la Independencia", "Igualapa", "Iliatenco", "Ixcateopan de Cuauhtémoc", "Juchitán", "Juan R. Escudero", "Leonardo Bravo", "Malinaltepec", "Mártir de Cuilapan", "Metlatónoc", "Mochitlán", "Olinalá", "Ometepec", "Pedro Ascencio Alquisiras", "Petatlán", "Pilcaya", "Pungarabato", "Quechultenango", "San Luis Acatlán", "San Marcos", "San Miguel Totolapan", "Taxco de Alarcón", "Tecoanapa", "Técpan de Galeana", "Teloloapan", "Tepecoacuilco de Trujano", "Tetipac", "Tixtla de Guerrero", "Tlacoachistlahuaca", "Tlacoapa", "Tlalchapa", "Tlalixtaquilla de Maldonado", "Tlapa de Comonfort", "Tlapehuala", "Xalpatláhuac", "Xochihuehuetlán", "Xochistlahuaca", "Zapotitlán Tablas", "Zihuatanejo de Azueta", "Zirándaro", "Zitlala"],
  "Hidalgo": ["Acatlán", "Acaxochitlán", "Actopan", "Agua Blanca de Iturbide", "Ajacuba", "Alfajayucan", "Almoloya", "Apan", "El Arenal", "Atitalaquia", "Atizapán", "Atotonilco el Grande", "Atotonilco de Tula", "Calnali", "Cardonal", "Cuautepec de Hinojosa", "Chapantongo", "Chapulhuacán", "Chilcuautla", "Eloxochitlán", "Emiliano Zapata", "Epazoyucan", "Francisco I. Madero", "Huasca de Ocampo", "Huautla", "Huazalingo", "Huehuetla", "Huejutla de Reyes", "Huichapan", "Ixmiquilpan", "Jacala de Ledezma", "Jaltocán", "Juárez Hidalgo", "Lolotla", "Metepec", "San Agustín Metzquititlán", "Metztitlán", "Mineral de la Reforma", "Mineral del Chico", "Mineral del Monte", "La Misión", "Mixquiahuala de Juárez", "Molango de Escamilla", "Nicolás Flores", "Nopala de Villagrán", "Omitlán de Juárez", "Pachuca de Soto", "Pacula", "Pisaflores", "Progreso de Obregón", "Mineral de la Reforma", "San Agustín Tlaxiaca", "San Bartolo Tutotepec", "San Felipe Orizatlán", "San Salvador", "Santiago de Anaya", "Santiago Tulantepec de Lugo Guerrero", "Singuilucan", "Tasquillo", "Tecozautla", "Tenango de Doria", "Tepeapulco", "Tepehuacán de Guerrero", "Tepeji del Río de Ocampo", "Tepetitlán", "Tetepango", "Tezontepec de Aldama", "Tianguistengo", "Tizayuca", "Tlahuelilpan", "Tlahuiltepa", "Tlanalapa", "Tlanchinol", "Tlaxcoapan", "Tolcayuca", "Tula de Allende", "Tulancingo de Bravo", "Villa de Tezontepec", "Xochiatipan", "Xochicoatlán", "Yahualica", "Zacualtipán de Ángeles", "Zapotlán de Juárez", "Zempoala", "Zimapán"],
  "Jalisco": ["Acatic", "Acatlán de Juárez", "Ahualulco de Mercado", "Amacueca", "Amatitán", "Ameca", "San Juanito de Escobedo", "Arandas", "El Arenal", "Atemajac de Brizuela", "Atengo", "Atenguillo", "Atotonilco el Alto", "Atoyac", "Autlán de Navarro", "Ayotlán", "Ayutla", "La Barca", "Bolaños", "Cabo Corrientes", "Casimiro Castillo", "Cihuatlán", "Zapotlán el Grande", "Cocula", "Colotlán", "Concepción de Buenos Aires", "Cuautitlán de García Barragán", "Cuautla", "Cuquío", "Chapala", "Chimaltitán", "Chiquilistlán", "Degollado","Encarnación de Díaz", "Etzatlán", "El Grullo", "Guachinango", "Guadalajara", "Hostotipaquillo", "Huejúcar", "Huejuquilla el Alto", "La Huerta", "Ixtlahuacán de los Membrillos", "Ixtlahuacán del Río", "Jalostotitlán", "Jamay", "Jesús María", "Jilotlán de los Dolores", "Jocotepec", "Juanacatlán", "Juchitlán", "Lagos de Moreno", "El Limón", "Magdalena", "Santa María del Oro", "La Manzanilla de la Paz", "Mascota", "Mazamitla", "Mexticacán", "Mezquitic", "Mixtlán", "Ocotlán", "Ojuelos de Jalisco", "Pihuamo", "Poncitlán", "Puerto Vallarta", "Villa Purificación", "Quitupan", "El Salto", "San Cristóbal de la Barranca", "San Diego de Alejandría", "San Gabriel", "San Juan de los Lagos", "San Julián", "San Marcos", "San Martín de Bolaños", "San Martín Hidalgo", "San Miguel el Alto", "Gómez Farías", "San Sebastián del Oeste", "Santa María de los Ángeles", "Sayula", "Tala", "Talpa de Allende", "Tamazula de Gordiano", "Tapalpa", "Tecalitlán", "Tecolotlán", "Techaluta de Montenegro", "Tenamaxtlán", "Teocaltiche", "Teocuitatlán de Corona", "Tepatitlán de Morelos", "Tequila", "Teuchitlán", "Tizapán el Alto", "Tlajomulco de Zúñiga", "Tlaquepaque", "Tolimán", "Tomatlán", "Tonalá", "Tonaya", "Tonila", "Totatiche", "Tototlán", "Tuxcacuesco", "Tuxcueca", "Tuxpan", "Unión de San Antonio", "Unión de Tula", "Valle de Guadalupe", "Valle de Juárez", "Villa Corona", "Villa Guerrero", "Villa Hidalgo", "Cañadas de Obregón", "Yahualica de González Gallo", "Zacoalco de Torres", "Zapopan", "Zapotiltic", "Zapotitlán de Vadillo", "Zapotlán del Rey", "Zapotlanejo"],
  "Estado de México": ["Acambay de Ruíz Castañeda", "Acolman", "Aculco", "Almoloya de Alquisiras", "Almoloya de Juárez", "Almoloya del Río", "Amanalco", "Amatepec", "Amecameca", "Apaxco", "Atenco", "Atizapán", "Atizapán de Zaragoza", "Atlacomulco", "Atlautla", "Axapusco", "Ayapango", "Calimaya", "Capulhuac", "Coacalco de Berriozábal", "Coatepec Harinas", "Cocotitlán", "Coyotepec", "Cuautitlán", "Chalco", "Chapa de Mota", "Chapultepec", "Chiautla", "Chicoloapan", "Chiconcuac", "Chimalhuacán", "Donato Guerra", "Ecatepec de Morelos", "Ecatzingo", "Huehuetoca", "Hueypoxtla", "Huixquilucan", "Isidro Fabela", "Ixtapaluca", "Ixtapan de la Sal", "Ixtapan del Oro", "Ixtlahuaca", "Xalatlaco", "Jaltenco", "Jilotepec", "Jilotzingo", "Jiquipilco", "Jocotitlán", "Joquicingo", "Juchitepec", "Lerma", "Malinalco", "Melchor Ocampo", "Metepec", "Mexicaltzingo", "Morelos", "Naucalpan de Juárez", "Nezahualcóyotl", "Nextlalpan", "Nicolás Romero", "Nopaltepec", "Ocoyoacac", "Ocuilan", "El Oro", "Otumba", "Otzoloapan", "Otzolotepec", "Ozumba", "Papalotla", "La Paz", "Polotitlán", "Rayón", "San Antonio la Isla", "San Felipe del Progreso", "San Martín de las Pirámides", "San Mateo Atenco", "San Simón de Guerrero", "Santo Tomás", "Soyaniquilpan de Juárez", "Sultepec", "Tecámac", "Tejupilco", "Temamatla", "Temascalapa", "Temascalcingo", "Temascaltepec", "Temoaya", "Tenancingo", "Tenango del Aire", "Tenango del Valle", "Teoloyucan", "Teotihuacán", "Tepetlaoxtoc", "Tepetlixpa", "Tepotzotlán", "Tequixquiac", "Texcaltitlán", "Texcalyacac", "Texcoco", "Tezoyuca", "Tianguistenco", "Timilpan", "Tlalmanalco", "Tlalnepantla de Baz", "Tlatlaya", "Toluca", "Tonatico", "Tultepec", "Tultitlán", "Valle de Bravo", "Valle de Chalco Solidaridad", "Villa de Allende", "Villa del Carbón", "Villa Guerrero", "Villa Victoria", "Xonacatlán", "Zacazonapan", "Zacualpan", "Zinacantepec", "Zumpahuacán", "Zumpango"],
  "Michoacán": ["Acuitzio", "Aguililla", "Álvaro Obregón", "Angamacutiro", "Angangueo", "Apatzingán", "Aporo", "Aquila", "Ario", "Arteaga", "Briseñas", "Buenavista", "Carácuaro", "Coahuayana", "Coalcomán de Vázquez Pallares", "Coeneo", "Contepec", "Copándaro", "Cotija", "Cuitzeo", "Charapan", "Charo", "Chavinda", "Cherán", "Chilchota", "Chinicuila", "Chucándiro", "Churintzio", "Churumuco", "Ecuandureo", "Epitacio Huerta", "Erongarícuaro", "Gabriel Zamora", "Hidalgo", "La Huacana", "Huandacareo", "Huaniqueo", "Huetamo", "Huiramba", "Indaparapeo", "Irimbo", "Ixtlán", "Jacona", "Jiménez", "Jiquilpan", "Juárez", "Jungapeo", "Lagunillas", "Madero", "Maravatío", "Marcos Castellanos", "Lázaro Cárdenas", "Morelia", "Morelos", "Múgica", "Nahuatzen", "Nocupétaro", "Nuevo Parangaricutiro", "Nuevo Urecho", "Numarán", "Ocampo", "Pajacuarán", "Panindícuaro", "Parácuaro", "Paracho", "Pátzcuaro", "Penjamillo", "Peribán", "La Piedad", "Purépero", "Puruándiro", "Queréndaro", "Quiroga", "Cojumatlán de Régules", "Los Reyes", "Sahuayo", "San Lucas", "Santa Ana Maya", "Salvador Escalante", "Senguio", "Susupuato", "Tacámbaro", "Tancítaro", "Tangamandapio", "Tangancícuaro", "Tanhuato", "Taretan", "Tarímbaro", "Tepalcatepec", "Tingambato", "Tingüindín", "Tiquicheo de Nicolás Romero", "Tlalpujahua", "Tlazazalca", "Tocumbo", "Tumbiscatío", "Turicato", "Tuxpan", "Tuzantla", "Tzintzuntzan", "Tzitzio", "Uruapan", "Venustiano Carranza", "Villamar", "Vista Hermosa", "Yurécuaro", "Zacapu", "Zamora", "Zináparo", "Zinapécuaro", "Ziracuaretiro", "Zitácuaro"],
  "Morelos": ["Amacuzac", "Atlatlahucan", "Axochiapan", "Ayala", "Coatlán del Río", "Cuautla", "Cuernavaca", "Emiliano Zapata", "Huitzilac", "Jantetelco", "Jiutepec", "Jojutla", "Jonacatepec", "Mazatepec", "Miacatlán", "Ocuituco", "Puente de Ixtla", "Temixco", "Temoac", "Tepalcingo", "Tepoztlán", "Tetecala", "Tetela del Volcán", "Tlalnepantla", "Tlaltizapán de Zapata", "Tlaquiltenango", "Tlayacapan", "Totolapan", "Xochitepec", "Yautepec", "Yecapixtla", "Zacatepec", "Zacuálpan"],
  "Nayarit": ["Acaponeta", "Ahuacatlán", "Amatlán de Cañas", "Bahía de Banderas", "Compostela", "Del Nayar", "Huajicori", "Ixtlán del Río", "Jala", "Xalisco", "La Yesca", "Rosamorada", "Ruíz", "San Blas", "San Pedro Lagunillas", "Santa María del Oro", "Santiago Ixcuintla", "Tecuala", "Tepic", "Tuxpan"],
  "Nuevo León": ["Abasolo", "Agualeguas", "Los Aldamas", "Allende", "Anáhuac", "Apodaca", "Aramberri", "Bustamante", "Cadereyta Jiménez", "Carmen", "Cerralvo", "Ciénega de Flores", "China", "Doctor Arroyo", "Doctor Coss", "Doctor González", "El Carmen", "Galeana", "García", "San Pedro Garza García", "General Bravo", "General Escobedo", "General Terán", "General Treviño", "General Zaragoza", "General Zuazua", "Guadalupe", "Los Herreras", "Higueras", "Hualahuises", "Iturbide", "Juárez", "Lampazos de Naranjo", "Linares", "Marín", "Melchor Ocampo", "Mier y Noriega", "Mina", "Montemorelos", "Monterrey", "Parás", "Pesquería", "Los Ramones", "Rayones", "Sabinas Hidalgo", "Salinas Victoria", "San Nicolás de los Garza", "Hidalgo", "Santa Catarina", "Santiago", "Vallecillo", "Villaldama"],
  "Oaxaca": ["Abejones",
  "San Miguel Tlacotepec",
  "Acatlán de Pérez Figueroa",
  "San Miguel Tulancingo",
  "Asunción Cacalotepec",
  "San Miguel Yotao",
  "Asunción Cuyotepeji",
  "San Nicolás",
  "Asunción Ixtaltepec",
  "San Nicolás Hidalgo",
  "Asunción Nochixtlán",
  "San Pablo Coatlán",
  "Asunción Ocotlán",
  "San Pablo Cuatro Venados",
  "Asunción Tlacolulita",
  "San Pablo Etla",
  "Ayotzintepec",
  "San Pablo Huitzo",
  "El Barrio de la Soledad",
  "San Pablo Huixtepec",
  "Calihualá",
  "San Pablo Macuiltianguis",
  "Candelaria Loxicha",
  "San Pablo Tijaltepec",
  "San Pablo Tijaltepec",
  "Ciénega de Zimatlán",
  "San Pablo Villa de Mitla",
  "Ciudad Ixtepec",
  "San Pablo Yaganiza",
  "Coatecas Altas",
  "San Pedro Amuzgos",
  "Coicoyán de las Flores",
  "San Pedro Apóstol",
  "La Compañía",
  "San Pedro Atoyac",
  "Concepción Buenavista",
  "San Pedro Cajonos",
  "Concepción Pápalo",
  "San Pedro Coxcaltepec Cántaros",
  "Constancia del Rosario",
  "San Pedro Comitancillo",
  "Cosolapa",
  "San Pedro el Alto",
  "Cosoltepec",
  "San Pedro Huamelula",
  "Cuilápam de Guerrero",
  "San Pedro Huilotepec",
  "Cuyamecalco Villa de Zaragoza",
  "San Pedro Ixcatlán",
  "Chahuites",
  "San Pedro Ixtlahuaca",
  "Chalcatongo de Hidalgo",
  "San Pedro Jaltepetongo",
  "Chiquihuitlán de Benito Juárez",
  "San Pedro Jicayán",
  "Heroica Ciudad de Ejutla de Crespo",
  "San Pedro Jocotipac",
  "Eloxochitlán de Flores Magón",
  "San Pedro Juchatengo",
  "El Espinal",
  "San Pedro Mártir",
  "Tamazulapam del Espíritu Santo",
  "San Pedro Mártir Quiechapa",
  "Fresnillo de Trujano",
  "San Pedro Mártir Yucuxaco",
  "Guadalupe Etla",
  "San Pedro Mixtepec - Distrito 22 ",
  "Guadalupe de Ramírez",
  "San Pedro Mixtepec - Distrito 26",
  "Guelatao de Juárez",
  "San Pedro Molinos",
  "Guevea de Humboldt",
  "San Pedro Nopala",
  "Mesones Hidalgo",
  "San Pedro Ocopetatillo",
  "Villa Hidalgo",
  "San Pedro Ocotepec",
  "Heroica Ciudad de Huajuapan de León",
  "San Pedro Pochutla",
  "Huautepec",
  "San Pedro Quiatoni",
  "Huautla de Jiménez",
  "San Pedro Sochiapam",
  "Ixtlán de Juárez",
  "San Pedro Tapanatepec",
  "Heroica Ciudad de Juchitán de Zaragoza",
  "San Pedro Taviche",
  "Loma Bonita",
  "San Pedro Teozacoalco",
  "Magdalena Apasco",
  "San Pedro Teutila",
  "Magdalena Jaltepec",
  "San Pedro Tidaá",
  "Santa Magdalena Jicotlán",
  "San Pedro Topiltepec",
  "Magdalena Mixtepec",
  "San Pedro Totolapa",
  "Magdalena Ocotlán",
  "Villa de Tututepec de Melchor Ocampo",
  "Magdalena Peñasco",
  "San Pedro Yaneri",
  "Magdalena Teitipac",
  "San Pedro Yólox",
  "Magdalena Tequisistlán",
  "San Pedro y San Pablo Ayutla",
  "Magdalena Tlacotepec",
  "Villa de Etla",
  "Magdalena Zahuatlán",
  "San Pedro y San Pablo Teposcolula",
  "Mariscala de Juárez",
  "San Pedro y San Pablo Tequixtepec",
  "Mártires de Tacubaya",
  "San Pedro Yucunama",
  "Matías Romero Avendaño",
  "San Raymundo Jalpan",
  "Mazatlán Villa de Flores",
  "San Sebastián Abasolo",
  "Miahuatlán de Porfirio Díaz",
  "San Sebastián Coatlán",
  "Mixistlán de la Reforma",
  "San Sebastián Ixcapa",
  "Monjas",
  "San Sebastián Nicananduta",
  "Natividad",
  "San Sebastián Río Hondo",
  "Nazareno Etla",
  "San Sebastián Tecomaxtlahuaca",
  "Nejapa de Madero",
  "San Sebastián Teitipac",
  "Ixpantepec Nieves",
  "San Sebastián Tutla",
  "Santiago Niltepec",
  "San Simón Almolongas",
  "Oaxaca de Juárez",
  "San Simón Zahuatlán",
  "Ocotlán de Morelos",
  "Santa Ana",
  "La Pe",
  "Santa Ana Ateixtlahuaca",
  "Pinotepa de Don Luis",
  "Santa Ana Cuauhtémoc",
  "Pluma Hidalgo",
  "Santa Ana del Valle",
  "San José del Progreso",
  "Santa Ana Tavela",
  "Putla Villa de Guerrero",
  "Santa Ana Tlapacoyan",
  "Santa Catarina Quioquitani",
  "Santa Ana Yareni",
  "Reforma de Pineda",
  "Santa Ana Zegache",
  "La Reforma",
  "Santa Catalina Quieri",
  "Reyes Etla",
  "Santa Catarina Cuixtla",
  "Rojas de Cuauhtémoc",
  "Santa Catarina Ixtepeji",
  "Salina Cruz",
  "Santa Catarina Juquila",
  "San Agustín Amatengo",
  "Santa Catarina Lachatao",
  "San Agustín Atenango",
  "Santa Catarina Loxicha",
  "San Agustín Chayuco",
  "Santa Catarina Mechoacán",
  "San Agustín de las Juntas",
  "Santa Catarina Minas",
  "San Agustín Etla",
  "Santa Catarina Quiané",
  "San Agustín Loxicha",
  "Santa Catarina Tayata",
  "San Agustín Tlacotepec",
  "Santa Catarina Ticuá",
  "San Agustín Yatareni",
  "Santa Catarina Yosonotú",
  "San Andrés Cabecera Nueva",
  "Santa Catarina Zapoquila",
  "San Andrés Dinicuiti",
  "Santa Cruz Acatepec",
  "San Andrés Huaxpaltepec",
  "Santa Cruz Amilpas",
  "San Andrés Huayapam",
  "Santa Cruz de Bravo",
  "San Andrés Ixtlahuaca",
  "Santa Cruz Itundujia",
  "San Andrés Lagunas",
  "Santa Cruz Mixtepec",
  "San Andrés Nuxiño",
  "Santa Cruz Nundaco",
  "San Andrés Paxtlán",
  "Santa Cruz Papalutla",
  "San Andrés Sinaxtla",
  "Santa Cruz Tacache de Mina",
  "San Andrés Solaga",
  "Santa Cruz Tacahua",
  "San Andrés Teotilálpam",
  "Santa Cruz Tayata",
  "San Andrés Tepetlapa",
  "Santa Cruz Xitla",
  "San Andrés Yaá",
  "Santa Cruz Xoxocotlán",
  "San Andrés Zabache",
  "Santa Cruz Zenzontepec",
  "San Andrés Zautla",
  "Santa Gertrudis",
  "San Antonino Castillo Velasco",
  "Santa Inés del Monte",
  "San Antonino el Alto",
  "Santa Inés Yatzeche",
  "San Antonino Monte Verde",
  "Santa Lucía del Camino",
  "San Antonio Acutla",
  "Santa Lucía Miahuatlán",
  "San Antonio de la Cal",
  "Santa Lucía Monteverde",
  "San Antonio Huitepec",
  "Santa Lucía Ocotlán",
  "San Antonio Nanahuatipam",
  "Santa María Alotepec",
  "San Antonio Sinicahua",
  "Santa María Apazco",
  "San Antonio Tepetlapa",
  "Santa María la Asunción",
  "San Baltazar Chichicapam",
  "Heroica Ciudad de Tlaxiaco",
  "San Baltazar Loxicha",
  "Ayoquezco de Aldama",
  "San Baltazar Yatzachi el Bajo",
  "Santa María Atzompa",
  "San Bartolo Coyotepec",
  "Santa María Camotlán",
  "San Bartolomé Ayautla",
  "Santa María Colotepec",
  "San Bartolomé Loxicha",
  "Santa María Cortijo",
  "San Bartolomé Quialana",
  "Santa María Coyotepec",
  "San Bartolomé Yucuañe",
  "Santa María Chachoapam",
  "San Bartolomé Zoogocho",
  "Villa de Chilapa de Díaz",
  "San Bartolo Soyaltepec",
  "Santa María Chilchotla",
  "San Bartolo Yautepec",
  "Santa María Chimalapa",
  "San Bernardo Mixtepec",
  "Santa María del Rosario",
  "San Blas Atempa",
  "Santa María del Tule",
  "San Carlos Yautepec",
  "Santa María Ecatepec",
  "San Cristóbal Amatlán",
  "Santa María Guelacé",
  "San Cristóbal Amoltepec",
  "Santa María Guienagati",
  "San Cristóbal Lachirioag",
  "Santa María Huatulco",
  "San Cristóbal Suchixtlahuaca",
  "Santa María Huazolotitlán",
  "San Dionisio del Mar",
  "Santa María Ipalapa",
  "San Dionisio Ocotepec",
  "Santa María Ixcatlán",
  "San Dionisio Ocotlán",
  "Santa María Jacatepec",
  "San Esteban Atatlahuca",
  "Santa María Jalapa del Marqués",
  "San Felipe Jalapa de Díaz",
  "Santa María Jaltianguis",
  "San Felipe Tejalapam",
  "Santa María Lachixío",
  "San Felipe Usila",
  "Santa María Mixtequilla",
  "San Francisco Cahuacúa",
  "Santa María Nativitas",
  "San Francisco Cajonos",
  "Santa María Nduayaco",
  "San Francisco Chapulapa",
  "Santa María Ozolotepec",
  "San Francisco Chindúa",
  "Santa María Pápalo",
  "San Francisco del Mar",
  "Santa María Peñoles",
  "San Francisco Huehuetlán",
  "Santa María Petapa",
  "San Francisco Ixhuatán",
  "Santa María Quiegolani",
  "San Francisco Jaltepetongo",
  "Santa María Sola",
  "San Francisco Lachigoló",
  "Santa María Tataltepec",
  "San Francisco Logueche",
  "Santa María Tecomavaca",
  "San Francisco Nuxaño",
  "Santa María Temaxcalapa",
  "San Francisco Ozolotepec",
  "Santa María Temaxcaltepec",
  "San Francisco Sola",
  "Santa María Teopoxco",
  "San Francisco Telixtlahuaca",
  "Santa María Tepantlali",
  "San Francisco Teopan",
  "Santa María Texcatitlán",
  "San Francisco Tlapancingo",
  "Santa María Tlahuitoltepec",
  "San Gabriel Mixtepec",
  "Santa María Tlalixtac",
  "San Ildefonso Amatlán",
  "Santa María Tonameca",
  "San Ildefonso Sola",
  "Santa María Totolapilla",
  "San Ildefonso Villa Alta",
  "Santa María Xadani",
  "San Jacinto Amilpas",
  "Santa María Yalina",
  "San Jacinto Tlacotepec",
  "Santa María Yavesía",
  "San Jerónimo Coatlán",
  "Santa María Yolotepec",
  "San Jerónimo Silacayoapilla",
  "Santa María Yosoyúa",
  "San Jerónimo Sosola",
  "Santa María Yucuhiti",
  "San Jerónimo Taviche",
  "Santa María Zacatepec",
  "San Jerónimo Tecoatl",
  "Santa María Zaniza",
  "San Jorge Nuchita",
  "Santa María Zoquitlán",
  "San José Ayuquila",
  "Santiago Amoltepec",
  "San José Chiltepec",
  "Santiago Apoala",
  "San José del Peñasco",
  "Santiago Apóstol",
  "San José Estancia Grande",
  "Santiago Astata",
  "San José Independencia",
  "Santiago Atitlán",
  "San José Lachiguirí",
  "Santiago Ayuquililla",
  "San José Tenango",
  "Santiago Cacaloxtepec",
  "San Juan Achiutla",
  "Santiago Camotlán",
  "San Juan Atepec",
  "Santiago Comaltepec",
  "Ánimas Trujano",
  "Santiago Chazumba",
  "San Juan Bautista Atatlahuca",
  "Santiago Choapam",
  "San Juan Bautista Coixtlahuaca",
  "Santiago del Río",
  "San Juan Bautista Cuicatlán",
  "Santiago Huajolotitlán",
  "San Juan Bautista Guelache",
  "Santiago Huauclilla",
  "San Juan Bautista Jayacatlán",
  "Santiago Ihuitlán Plumas",
  "San Juan Bautista Lo de Soto",
  "Santiago Ixcuintepec",
  "San Juan Bautista Suchitepec",
  "Santiago Ixtayutla",
  "San Juan Bautista Tlacoatzintepec",
  "Santiago Jamiltepec",
  "San Juan Bautista Tlachichilco",
  "Santiago Jocotepec",
  "San Juan Bautista Tuxtepec",
  "Santiago Juxtlahuaca",
  "San Juan Cacahuatepec",
  "Santiago Lachiguiri",
  "San Juan Cieneguilla",
  "Santiago Lalopa",
  "San Juan Coatzospam",
  "Santiago Laollaga",
  "San Juan Colorado",
  "Santiago Laxopa",
  "San Juan Comaltepec",
  "Santiago Llano Grande",
  "San Juan Cotzocón",
  "Santiago Matatlán",
  "San Juan Chicomezúchil",
  "Santiago Miltepec",
  "San Juan Chilateca",
  "Santiago Minas",
  "San Juan del Estado",
  "Santiago Nacaltepec",
  "San Juan del Río",
  "Santiago Nejapilla",
  "San Juan Diuxi",
  "Santiago Nundiche",
  "San Juan Evangelista Analco",
  "Santiago Nuyoó",
  "San Juan Guelavía",
  "Santiago Pinotepa Nacional",
  "San Juan Guichicovi",
  "Santiago Suchilquitongo",
  "San Juan Ihualtepec",
  "Santiago Tamazola",
  "San Juan Juquila Mixes",
  "Santiago Tapextla",
  "San Juan Juquila Vijanos",
  "Villa Tejúpam de la Unión",
  "San Juan Lachao",
  "Santiago Tenango",
  "San Juan Lachigalla",
  "Santiago Tepetlapa",
  "San Juan Lajarcia",
  "Santiago Tetepec",
  "San Juan Lalana",
  "Santiago Texcalcingo",
  "San Juan de los Cues",
  "Santiago Textitlán",
  "San Juan Mazatlán",
  "Santiago Tilantongo",
  "San Juan Mixtepec -Distrito 08",
  "Santiago Tillo",
  "San Juan Mixtepec -Distrito 26",
  "Santiago Tlazoyaltepec",
  "San Juan Ñumí",
  "Santiago Xanica",
  "San Juan Ozolotepec",
  "Santiago Xiacuí",
  "San Juan Petlapa",
  "Santiago Yaitepec",
  "San Juan Quiahije",
  "Santiago Yaveo",
  "San Juan Quiotepec",
  "Santiago Yolomécatl",
  "San Juan Sayultepec",
  "Santiago Yosondúa",
  "San Juan Tabaá",
  "Santiago Yucuyachi",
  "San Juan Tamazola",
  "Santiago Zacatepec",
  "San Juan Teita",
  "Santiago Zoochila",
  "San Juan Teitipac",
  "Nuevo Zoquiapam",
  "San Juan Tepeuxila",
  "Santo Domingo Ingenio",
  "San Juan Teposcolula",
  "Santo Domingo Albarradas",
  "San Juan Yaeé",
  "Santo Domingo Armenta",
  "San Juan Yatzona",
  "Santo Domingo Chihuitán",
  "San Juan Yucuita",
  "Santo Domingo de Morelos",
  "San Lorenzo",
  "Santo Domingo Ixcatlán",
  "San Lorenzo Albarradas",
  "Santo Domingo Nuxaá",
  "San Lorenzo Cacaotepec",
  "Santo Domingo Ozolotepec",
  "San Lorenzo Cuaunecuiltitla",
  "Santo Domingo Petapa",
  "San Lorenzo Texmelucan",
  "Santo Domingo Roayaga",
  "San Lorenzo Victoria",
  "Santo Domingo Tehuantepec",
  "San Lucas Camotlán",
  "Santo Domingo Teojomulco",
  "San Lucas Ojitlán",
  "Santo Domingo Tepuxtepec",
  "San Lucas Quiaviní",
  "Santo Domingo Tlatayapam",
  "San Lucas Zoquiapam",
  "Santo Domingo Tomaltepec",
  "San Luis Amatlán",
  "Santo Domingo Tonalá",
  "San Marcial Ozolotepec",
  "Santo Domingo Tonaltepec",
  "San Marcos Arteaga",
  "Santo Domingo Xagacía",
  "San Martín de los Cansecos",
  "Santo Domingo Yanhuitlán",
  "San Martín Huamelulpam",
  "Santo Domingo Yodohino",
  "San Martín Itunyoso",
  "Santo Domingo Zanatepec",
  "San Martín Lachilá",
  "Santos Reyes Nopala",
  "San Martín Peras",
  "Santos Reyes Pápalo",
  "San Martín Tilcajete",
  "Santos Reyes Tepejillo",
  "San Martín Toxpalan",
  "Santos Reyes Yucuná",
  "San Martín Zacatepec",
  "Santo Tomás Jalieza",
  "San Mateo Cajonos",
  "Santo Tomás Mazaltepec",
  "Capulálpam de Méndez",
  "Santo Tomás Ocotepec",
  "San Mateo del Mar",
  "Santo Tomás Tamazulapan",
  "San Mateo Yoloxochitlán",
  "San Vicente Coatlán",
  "San Mateo Etlatongo",
  "San Vicente Lachixío",
  "San Mateo Nejapam",
  "San Vicente Nuñú",
  "San Mateo Peñasco",
  "Silacayoapam",
  "San Mateo Piñas",
  "Sitio de Xitlapehua",
  "San Mateo Río Hondo",
  "Soledad Etla",
  "San Mateo Sindihui",
  "Villa de Tamazulapam del Progreso",
  "San Mateo Tlapiltepec",
  "Tanetze de Zaragoza",
  "San Melchor Betaza",
  "Taniche",
  "San Miguel Achiutla",
  "Tataltepec de Valdés",
  "San Miguel Ahuehuetitlán",
  "Teococuilco de Marcos Pérez",
  "San Miguel Aloápam",
  "Teotitlán de Flores Magón",
  "San Miguel Amatitlán",
  "Teotitlán del Valle",
  "San Miguel Amatlán",
  "Teotongo",
  "San Miguel Coatlán",
  "Tepelmeme Villa de Morelos",
  "San Miguel Chicahua",
  "Tezoatlán de Segura y Luna",
  "San Miguel Chimalapa",
  "San Jerónimo Tlacochahuaya",
  "San Miguel del Puerto",
  "Tlacolula de Matamoros",
  "San Miguel del Río",
  "Tlacotepec Plumas",
  "San Miguel Ejutla",
  "Tlalixtac de Cabrera",
  "San Miguel el Grande",
  "Totontepec Villa de Morelos",
  "San Miguel Huautla",
  "Trinidad Zaachila",
  "San Miguel Mixtepec",
  "La Trinidad Vista Hermosa",
  "San Miguel Panixtlahuaca",
  "Unión Hidalgo",
  "San Miguel Peras",
  "Valerio Trujano",
  "San Miguel Piedras",
  "San Juan Bautista Valle Nacional",
  "San Miguel Quetzaltepec",
  "Villa Díaz Ordaz",
  "San Miguel Santa Flor",
  "Yaxe",
  "Villa Sola de Vega",
  "Magdalena Yodocono de Porfirio Díaz",
  "San Miguel Soyaltepec",
  "Yogana",
  "San Miguel Suchixtepec",
  "Yutanduchi de Guerrero",
  "Villa Talea de Castro",
  "Villa de Zaachila",
  "San Miguel Tecomatlán",
  "Zapotitlán del Río",
  "San Miguel Tenango",
  "Zapotitlán Lagunas",
  "San Miguel Tequixtepec",
  "Zapotitlán Palmas",
  "San Miguel Tilquiapam",
  "Santa Inés de Zaragoza",
  "San Miguel Tlacamama",
  "Zimatlán de Álvarez"],
  "Puebla": ["Acajete", "Acateno", "Acatlán", "Acatzingo", "Acteopan", "Ahuacatlán", "Ahuatlán", "Ahuazotepec", "Ahuehuetitla", "Ajalpan", "Albino Zertuche", "Aljojuca", "Altepexi", "Amixtlán", "Amozoc", "Aquixtla", "Atempan", "Atexcal", "Atlixco", "Atoyatempan", "Atzala", "Atzitzihuacán", "Atzitzintla", "Axutla", "Ayotoxco de Guerrero", "Calpan", "Caltepec", "Camocuautla", "Cañada Morelos", "Caxhuacan", "Chalchicomula de Sesma", "Chapulco", "Chiautla", "Chiautzingo", "Chiconcuautla", "Chichiquila", "Chietla", "Chigmecatitlán", "Chignahuapan", "Chignautla", "Chila", "Chila de la Sal", "Chilchotla", "Chinantla", "Coatepec", "Coatzingo", "Cohetzala", "Cohuecan", "Coronango", "Coxcatlán", "Coyomeapan", "Coyotepec", "Cuapiaxtla de Madero", "Cuautempan", "Cuautinchán", "Cuautlancingo", "Cuayuca de Andrade", "Cuetzalan del Progreso", "Cuyoaco", "Domingo Arenas", "Eloxochitlán", "Epatlán", "Esperanza", "Francisco Z. Mena", "General Felipe Ángeles", "Guadalupe", "Guadalupe Victoria", "Hermenegildo Galeana", "Honey", "Huaquechula", "Huatlatlauca", "Huauchinango", "Huehuetla", "Huehuetlán el Chico", "Huejotzingo", "Hueyapan", "Hueytamalco", "Hueytlalpan", "Huitzilán de Serdán", "Huitziltepec", "Ixcamilpa de Guerrero", "Ixcaquixtla", "Ixtacamaxtitlán", "Ixtepec", "Izúcar de Matamoros", "Jalpan", "Jolalpan", "Jonotla", "Jopala", "Juan C. Bonilla", "Juan Galindo", "Juan N. Méndez", "La Magdalena Tlatlauquitepec", "Lafragua", "Libres", "Los Reyes de Juárez", "Mazapiltepec de Juárez", "Mixtla", "Molcaxac", "Naupan", "Nauzontla", "Nealtican", "Nicolás Bravo", "Nopalucan", "Ocotepec", "Ocoyucan", "Olintla", "Oriental", "Pahuatlán", "Palmar de Bravo", "Pantepec", "Petlalcingo", "Piaxtla", "Puebla", "Quecholac", "Quimixtlán", "Rafael Lara Grajales", "San Andrés Cholula", "San Antonio Cañada", "San Diego la Mesa Tochimiltzingo", "San Felipe Teotlalcingo", "San Felipe Tepatlán", "San Gabriel Chilac", "San Gregorio Atzompa", "San Jerónimo Tecuanipan", "San Jerónimo Xayacatlán", "San José Chiapa", "San José Miahuatlán", "San Juan Atenco", "San Juan Atzompa", "San Martín Texmelucan", "San Martín Totoltepec", "San Matías Tlalancaleca", "San Miguel Ixitlán", "San Miguel Xoxtla", "San Nicolás Buenos Aires", "San Nicolás de los Ranchos", "San Pablo Anicano", "San Pedro Cholula", "San Pedro Yeloixtlahuaca", "San Salvador el Seco", "San Salvador el Verde", "San Salvador Huixcolotla", "San Sebastián Tlacotepec", "Santa Catarina Tlaltempan", "Santa Inés Ahuatempan", "Santa Isabel Cholula", "Santiago Miahuatlán", "Santo Tomás Hueyotlipan", "Soltepec", "Tecali de Herrera", "Tecamachalco", "Tecomatlán", "Tehuacán", "Tehuitzingo", "Tenampulco", "Teopantlán", "Teotlalco", "Tepanco de López", "Tepango de Rodríguez", "Tepatlaxco de Hidalgo", "Tepeaca", "Tepemaxalco", "Tepeojuma", "Tepetzintla", "Tepexco", "Tepexi de Rodríguez", "Tepeyahualco", "Tepeyahualco de Cuauhtémoc", "Tetela de Ocampo", "Teteles de Ávila Castillo", "Teziutlán", "Tianguismanalco", "Tilapa", "Tlachichuca", "Tlacotepec de Benito Juárez", "Tlacuilotepec", "Tlahuapan", "Tlaltenango", "Tlanepantla", "Tlaola", "Tlapacoya", "Tlapanalá", "Tlatlauquitepec", "Tlaxco", "Tochimilco", "Tochtepec", "Totoltepec de Guerrero", "Tulcingo", "Tuzamapan de Galeana", "Tzicatlacoyan", "Venustiano Carranza", "Vicente Guerrero", "Xayacatlán de Bravo", "Xicotepec", "Xicotlán", "Xiutetelco", "Xochiapulco", "Xochiltepec", "Xochitlán de Vicente Suárez", "Xochitlán Todos Santos", "Yaonáhuac", "Yehualtepec", "Zacapala", "Zacapoaxtla", "Zacatlán", "Zapotitlán", "Zapotitlán de Méndez", "Zaragoza", "Zautla", "Zihuateutla"],
  "Querétaro": ["Amealco de Bonfil", "Arroyo Seco", "Cadereyta de Montes", "Colón", "Corregidora", "El Marqués", "Ezequiel Montes", "Huimilpan", "Jalpan de Serra", "Landa de Matamoros", "Pedro Escobedo", "Peñamiller", "Pinal de Amoles", "Querétaro", "San Joaquín", "San Juan del Río", "Tequisquiapan", "Tolimán"],
  "Quintana Roo":["Bacalar", "Benito Juárez", "Cozumel", "Felipe Carrillo Puerto", "Isla Mujeres", "José María Morelos", "Lázaro Cárdenas", "Othón P. Blanco", "Puerto Morelos", "Solidaridad", "Tulum"],
  "San Luis Potosí":["Ahualulco", "Alaquines", "Aquismón", "Armadillo de los Infante", "Axtla de Terrazas", "Cárdenas", "Catorce", "Cedral", "Cerritos", "Cerro de San Pedro", "Charcas", "Ciudad del Maíz", "Ciudad Fernández", "Ciudad Valles", "Coxcatlán", "Ebano", "El Naranjo", "Guadalcázar", "Huehuetlán", "Lagunillas", "Matehuala", "Matlapa", "Mexquitic de Carmona", "Moctezuma", "Rayón", "Rioverde", "Salinas", "San Antonio", "San Ciro de Acosta", "San Luis Potosí", "San Martín Chalchicuautla", "San Nicolás Tolentino", "San Vicente Tancuayalab", "Santa Catarina", "Santa María del Río", "Santo Domingo", "Soledad de Graciano Sánchez", "Tamasopo", "Tamazunchale", "Tampacán", "Tampamolón Corona", "Tamuín", "Tanlajás", "Tanquián de Escobedo", "Tierra Nueva", "Vanegas", "Venado", "Villa de Arista", "Villa de Arriaga", "Villa de Guadalupe", "Villa de la Paz", "Villa de Ramos", "Villa de Reyes", "Villa Hidalgo", "Villa Juárez", "Xilitla", "Zaragoza"],
  "Sinaloa":["Ahome", "Angostura", "Badiraguato", "Choix", "Concordia", "Cosalá", "Culiacán", "El Fuerte", "Elota", "Escuinapa", "Guasave", "Mazatlán", "Mocorito", "Navolato", "Rosario", "Salvador Alvarado", "San Ignacio", "Sinaloa"],
  "Tabasco":["Balancán", "Cárdenas", "Centla", "Centro", "Comalcalco", "Cunduacán", "Emiliano Zapata", "Huimanguillo", "Jalapa", "Jalpa de Méndez", "Jonuta", "Macuspana", "Nacajuca", "Paraíso", "Tacotalpa", "Teapa", "Tenosique"],
  "Tlaxcala":["Acuamanala de Miguel Hidalgo", "Altzayanca", "Amaxac de Guerrero", "Apetatitlán de Antonio Carvajal", "Atlangatepec", "Benito Juárez", "Calpulalpan", "Chiautempan", "Contla de Juan Cuamatzi", "Cuapiaxtla", "Cuaxomulco", "El Carmen Tequexquitla", "Emiliano Zapata", "Españita", "Huamantla", "Hueyotlipan", "Ixtacuixtla de Mariano Matamoros", "Ixtenco", "La Magdalena Tlaltelulco", "Lázaro Cárdenas", "Mazatecochco de José María Morelos", "Muñoz de Domingo Arenas", "Nanacamilpa de Mariano Arista", "Natívitas", "Panotla", "Papalotla de Xicohténcatl", "San Damián Texóloc", "San Francisco Tetlanohcan", "San Jerónimo Zacualpan", "San José Teacalco", "San Juan Huactzinco", "San Lorenzo Axocomanitla", "San Lucas Tecopilco", "San Pablo del Monte", "Sanctórum de Lázaro Cárdenas", "Santa Ana Nopalucan", "Santa Apolonia Teacalco", "Santa Catarina Ayometla", "Santa Cruz Quilehtla", "Santa Cruz Tlaxcala", "Santa Isabel Xiloxoxtla", "Tenancingo", "Teolocholco", "Tepetitla de Lardizábal", "Tepeyanco", "Terrenate", "Tetla de la Solidaridad", "Tetlatlahuca", "Tlaxcala", "Tlaxco", "Tocatlán", "Totolac", "Tzompantepec", "Xaloztoc", "Xaltocan", "Xicohtzinco", "Yauhquemehcan", "Zacatelco", "Ziltlaltépec de Trinidad Sánchez Santos"],
 "Veracruz":["Acayucan", "Actopan", "Acula", "Acultzingo", "Agua Dulce", "Álamo Temapache", "Alpatláhuac", "Alto Lucero de Gutiérrez Barrios", "Altotonga", "Alvarado", "Amatitlán", "Amatlán de los Reyes", "Angel R. Cabada", "Apazapan", "Aquila", "Astacinga", "Atlahuilco", "Atoyac", "Atzacan", "Atzalan", "Ayahualulco", "Banderilla", "Benito Juárez", "Boca del Río", "Calcahualco", "Camarón de Tejeda", "Camerino Z. Mendoza", "Carlos A. Carrillo", "Carrillo Puerto", "Castillo de Teayo", "Catemaco", "Cazones de Herrera", "Cerro Azul", "Chacaltianguis", "Chalma", "Chiconamel", "Chiconquiaco", "Chicontepec", "Chinameca", "Chinampa de Gorostiza", "Chocamán", "Chontla", "Chumatlán", "Citlaltépetl", "Coacoatzintla", "Coahuitlán", "Coatepec", "Coatzacoalcos", "Coatzintla", "Comapa", "Córdoba", "Cosamaloapan de Carpio", "Cosautlán de Carvajal", "Coscomatepec", "Cosoleacaque", "Cotaxtla", "Coxquihui", "Coyutla", "Cuichapa", "Cuitláhuac", "El Higo", "Emiliano Zapata", "Espinal", "Filomeno Mata", "Fortín", "Gutiérrez Zamora", "Hidalgotitlán", "Huatusco", "Huayacocotla", "Hueyapan de Ocampo", "Huiloapan de Cuauhtémoc", "Ignacio de la Llave", "Ilamatlán", "Isla", "Ixcatepec", "Ixhuacán de los Reyes", "Ixhuatlán de Madero", "Ixhuatlancillo", "Ixhuatlán del Café", "Ixhuatlán del Sureste", "Ixhuatlán del Sureste", "Ixmatlahuacan", "Ixtaczoquitlán", "Jalacingo", "Jalcomulco", "Jáltipan", "Jamapa", "Jesús Carranza", "Jilotepec", "José Azueta", "Juan Rodríguez Clara", "Juchique de Ferrer", "La Antigua", "La Perla", "Landero y Coss", "Las Choapas", "Las Minas", "Las Vigas de Ramírez", "Lerdo de Tejada", "Los Reyes", "Magdalena", "Maltrata", "Manlio Fabio Altamirano", "Mariano Escobedo", "Martínez de la Torre", "Mecatlán", "Mecayapan", "Medellín", "Miahuatlán", "Minatitlán", "Misantla", "Mixtla de Altamirano", "Moloacán", "Nanchital de Lázaro Cárdenas del Río", "Naolinco", "Naranjal", "Naranjos Amatlán", "Nautla", "Nogales", "Oluta", "Omealca", "Orizaba", "Otatitlán", "Oteapan", "Ozuluama de Mascareñas", "Pajapan", "Pánuco", "Papantla", "Paso de Ovejas", "Paso del Macho", "Perote", "Platón Sánchez", "Playa Vicente", "Poza Rica de Hidalgo", "Pueblo Viejo", "Puente Nacional", "Rafael Delgado", "Rafael Lucio", "Río Blanco", "Saltabarranca", "San Andrés Tenejapan", "San Andrés Tuxtla", "San Juan Evangelista", "San Rafael", "Santiago Sochiapan", "Santiago Tuxtla", "Sayula de Alemán", "Sochiapa", "Soconusco", "Soledad Atzompa", "Soledad de Doblado", "Soteapan", "Tamalín", "Tamiahua", "Tampico Alto", "Tancoco", "Tantima", "Tantoyuca", "Tatahuicapan de Juárez", "Tatatila", "Tecolutla", "Tehuipango", "Tempoal", "Tenampa", "Tenochtitlán", "Teocelo", "Tepatlaxco", "Tepetlán", "Tepetzintla", "Tequila", "Texcatepec", "Texhuacán", "Texistepec", "Tezonapa", "Tierra Blanca", "Tihuatlán", "Tlachichilco", "Tlacojalpan", "Tlacolulan", "Tlacotalpan", "Tlacotepec de Mejía", "Tlalixcoyan", "Tlalnelhuayocan", "Tlaltetela", "Tlapacoyan", "Tlaquilpa", "Tlilapan", "Tomatlán", "Tonayán", "Totutla", "Tres Valles", "Túxpam", "Tuxtilla", "Ursulo Galván", "Uxpanapa", "Vega de Alatorre", "Veracruz", "Villa Aldama", "Xalapa", "Xico", "Xoxocotla", "Yanga", "Yecuatla", "Zacualpan", "Zaragoza", "Zentla", "Zongolica", "Zontecomatlán de López y Fuentes", "Zozocolco de Hidalgo"],
  "Yucatán":["Abalá", "Acanceh", "Akil", "Baca", "Bokobá", "Buctzotz", "Cacalchén", "Calotmul", "Cansahcab", "Cantamayec", "Celestún", "Cenotillo", "Chacsinkín", "Chankom", "Chapab", "Chemax", "Chichimilá", "Chicxulub Pueblo", "Chikindzonot", "Chocholá", "Chumayel", "Conkal", "Cuncunul", "Cuzamá", "Dzán", "Dzemul", "Dzidzantún", "Dzilam de Bravo", "Dzilam González", "Dzitás", "Dzoncauich", "Espita", "Halachó", "Hocabá", "Hoctún", "Homún", "Huhí", "Hunucmá", "Ixil", "Izamal", "Kanasín", "Kantunil", "Kaua", "Kinchil", "Kopomá", "Mama", "Maní", "Maxcanú", "Mayapán", "Mérida", "Mocochá", "Motul", "Muna", "Muxupip", "Opichén", "Oxkutzcab", "Panabá", "Peto", "Progreso", "Quintana Roo", "Río Lagartos", "Sacalum", "Samahil", "San Felipe", "Sanahcat", "Santa Elena", "Seyé", "Sinanché", "Sotuta", "Sucilá", "Sudzal", "Suma", "Tahdziú", "Tahmek", "Teabo", "Tecoh", "Tekal de Venegas", "Tekantó", "Tekax", "Tekit", "Tekom", "Telchac Pueblo", "Telchac Puerto", "Temax", "Temozón", "Tepakán", "Tetiz", "Teya", "Ticul", "Timucuy", "Tinum", "Tixcacalcupul", "Tixkokob", "Tixmehuac", "Tixpéhual", "Tizimín", "Tunkás", "Tzucacab", "Uayma", "Ucú", "Umán", "Valladolid", "Xocchel", "Yaxcabá", "Yaxkukul", "Yobaín"],
  "Zacatecas": ["Apozol", "Apulco", "Atolinga", "Benito Juárez", "Calera", "Cañitas de Felipe Pescador", "Chalchihuites", "Concepción del Oro", "Cuauhtémoc", "El Plateado de Joaquín Amaro", "El Salvador", "Fresnillo", "Genaro Codina", "General Enrique Estrada", "General Francisco R. Murguía", "General Pánfilo Natera", "Guadalupe", "Huanusco", "Jalpa", "Jerez", "Jiménez del Teul", "Juan Aldama", "Juchipila", "Loreto", "Luis Moya", "Mazapil", "Melchor Ocampo", "Mezquital del Oro", "Miguel Auza", "Momax", "Monte Escobedo", "Morelos", "Moyahua de Estrada", "Nochistlán de Mejía", "Noria de Ángeles", "Ojocaliente", "Pánuco", "Pinos", "Río Grande", "Sain Alto", "Santa María de la Paz", "Sombrerete", "Susticacán", "Tabasco", "Tepechitlán", "Tepetongo", "Teúl de González Ortega", "Tlaltenango de Sánchez Román", "Trancoso", "Trinidad García de la Cadena", "Valparaíso", "Vetagrande", "Villa de Cos", "Villa García", "Villa González Ortega", "Villa Hidalgo", "Villanueva", "Zacatecas"],
};

// Obtener el select de estados y municipios
var estados = document.getElementById("estados");
var municipios = document.getElementById("municipios");

// Agregar un listener al select de estados para actualizar la lista de municipios
estados.addEventListener("change", function() {
  // Obtener el estado seleccionado
  var estadoSeleccionado = this.value;
  
  // Obtener la lista de municipios correspondiente al estado seleccionado
  var municipiosDeEstado = municipiosPorEstado[estadoSeleccionado];
  
  // Limpiar la lista de municipios
  municipios.innerHTML = "";
  
  // Agregar un option por cada municipio del estado seleccionado
  municipiosDeEstado.forEach(function(municipio) {
    var option = document.createElement("option");
    option.value = municipio;
    option.textContent = municipio;
    municipios.appendChild(option);
  });
  
  // Si no hay municipios en el estado seleccionado, mostrar un mensaje de error
  if (municipiosDeEstado.length === 0) {
    var option = document.createElement("option");
    option.textContent = "No se encontraron municipios para este estado";
    municipios.appendChild(option);
  }
});
